---
 - hosts: [hosts]
   remote_user: [user]
   vars:
     new_password: 'password hash here'
     machine_user: 'user'
   tasks:
   - name: Change user's password to new one
     user:
       name: "{{machine_user}}"
       password: "{{new_password}}"
       state: present

